version: '3.0'
services:
  dev:
    image: dockerizedgraphql/cql-dev
    container_name: 'cql-dev-hot'
    ports:
      - '8081:8081'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev:hot
volumes:
  node_modules:
